image: fedora/latest
packages:
  - dotnet
  - wget
  - unzip
tasks:
  - download-dalamud: |
      mkdir dalamud
      cd dalamud
      wget https://github.com/goatcorp/dalamud-distrib/raw/main/latest.zip
      unzip latest.zip
      rm latest.zip
  - build-plugin: |
      cd Namingway/Namingway
      dotnet build -c Release -p:IsCI=true
artifacts:
  - Namingway/Namingway/bin/Release/net5-windows/Namingway/latest.zip
